### ISSUE TITLE
LUA in BG/open world (often, not seldom)

### ISSUE THREAD

**Issue by luckyjoker1979** [TLDRMissions/macroautotarget#1]
5x ...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:88: script ran too long
[string "@ArenaTargetHealer/mainline/ArenaTargetHealer.lua"]:88: in function <...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:85>
[string "@ArenaTargetHealer/mainline/ArenaTargetHealer.lua"]:116: in function <...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:115>
[string "@ArenaTargetHealer/mainline/ArenaTargetHealer.lua"]:226: in function <...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:120>

Locals:
command = "#RTD"
unitID = "player"
rosterIndex = 15
(for index) = 12
(for limit) = 138
(for step) = 1
i = 12
name = "A-Binder-Cursor"
icon = 462650
body = "#showtooltip
/use [known:109248,@cursor]Bindender Schuss
"
(*temporary) = 462650
(*temporary) = "#showtooltip
/use [known:109248,@cursor]Bindender Schuss
"
(*temporary) = nil
(*temporary) = "#showtooltip
/use [known:Schattenminik] Schattenmimik
/use [known:Berserker][combat] Berserker
/use [pet:Katze] Schleichen
"
(*temporary) = "#RTD"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"

**Comment by teelolws** [comment]
How many macros do you have?

**Comment by luckyjoker1979** [comment]
With ATH inside? 4-5. Dont use them in these situations.

**Comment by teelolws** [comment]
No, in total, including irrelevant macros.

**Comment by luckyjoker1979** [comment]
There are 127 macros in /m-Menu. I probably have more than 100 of them in my hunter specialization. I'm blind and need macros to be able to play WoW.

**Comment by teelolws** [comment]
Allright. I'll fill out all my macro slots and see what happens.

**Comment by luckyjoker1979** [comment]
:) Thank you.
