### ISSUE TITLE
CPU-Issue since the new patch

### ISSUE THREAD

**Issue by luckyjoker1979** [TLDRMissions/macroautotarget#2]
Hello, thanks again for the update, now the LUA error is gone. 
There is now a new problem: CPU usage is now in first place, ahead of Weakaura & Co. and not even in the arena but without war mode in the open world. Specially switched off world mode for the test. :) 
Please take a look on it. Measured with Addons CPU Usage and Addon Usage.

**Comment by teelolws** [comment]
It should only be doing anything when:
- Your group or raid roster changes (someone joins, leaves, gets moved)
- You or someone in your group changes spec
- You enter the prep stage of arena
- Opponents in arena change
- You were in combat when any of the above happened and now left combat

It can be CPU intensive to read all your macros, so a bit of usage is to be expected. If the addon is chewing up CPU usage when none of the above situations happens, then that is a problem.

**Comment by luckyjoker1979** [comment]
What do you think if the addon only works in the arena? That's what it's there for, then the CPU problems in the open world and in the BG would certainly be solved.

**Comment by teelolws** [comment]
It hasn't been an arena-only addon for a while. I expanded it to be used to change party and raid targets in early Dragonflight.

![image](https://github.com/user-attachments/assets/b6732eca-b6e3-4cff-a6d6-a856d348cc4a)

**Comment by luckyjoker1979** [comment]
How do you feel about making this optionally switchable?

**Comment by teelolws** [comment]
Adding options requires importing the Ace3 libraries to setup an options panel, which will involve more processing time than the alternative I've come up with: I've throttled it to not reload your macros into memory and check them more often than 5s.

**Comment by luckyjoker1979** [comment]
Hi, first on fight in bg, no changes before. 
1x ...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:117: script ran too long
[string "@ArenaTargetHealer/mainline/ArenaTargetHealer.lua"]:117: in function <...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:105>
[string "@ArenaTargetHealer/mainline/ArenaTargetHealer.lua"]:143: in function <...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:142>
[string "@ArenaTargetHealer/mainline/ArenaTargetHealer.lua"]:275: in function <...Ons/ArenaTargetHealer/mainline/ArenaTargetHealer.lua:147>

Locals:
command = "#RTD"
unitID = "player"
rosterIndex = 35
(for index) = 49
(for limit) = 138
(for step) = 1
macroIndex = 49
name = "ASV-Raptor-Falke"
icon = 612363
body = "#showtooltip
/cleartarget [help][noharm]
/targetenemy [noexists]
/cancelaura Aspekt der Schildkröte
/use Aspekt des Adlers
/use [known:186270]Raptorstoß
/use [known:259387]Mungobiss
/use [combat]Berserker
/klick PetActionButton2
/petattack
"
cache = "#showtooltip
/cleartarget [help][noharm]
/targetenemy [noexists]
/cancelaura Aspekt der Schildkröte
/use Aspekt des Adlers
/use [known:186270]Raptorstoß
/use [known:259387]Mungobiss
/use [combat]Berserker
/klick PetActionButton2
/petattack
"
secondaryMatch = nil
alternateMatch = nil
(*temporary) = "#showtooltip
/cleartarget [help][noharm]
/targetenemy [noexists]
/cancelaura Aspekt der Schildkröte
/use Aspekt des Adlers
/use [known:186270]Raptorstoß
/use [known:259387]Mungobiss
/use [combat]Berserker
/klick PetActionButton2
/petattack
"
(*temporary) = "#RTD[0-9]+"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
macroCache = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
 99 = <table> {
 }
 100 = <table> {
 }
 101 = <table> {
 }
 102 = <table> {
 }
 103 = <table> {
 }
 121 = <table> {
 }
 122 = <table> {
 }
 123 = <table> {
 }
 124 = <table> {
 }
 125 = <table> {
 }
 126 = <table> {
 }
 127 = <table> {
 }
 128 = <table> {
 }
 138 = <table> {
 }
 131 = <table> {
 }
 132 = <table> {
 }
 133 = <table> {
 }
 134 = <table> {
 }
 135 = <table> {
 }
 136 = <table> {
 }
 129 = <table> {
 }
 137 = <table> {
 }
 130 = <table> {
 }
}

**Comment by luckyjoker1979** [comment]
Thank you very much, I will test it.
